# Generated by Django 4.2.1 on 2023-05-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
